package naval.dominio;



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ActividadInvestigacion generated by hbm2java
 */
@Entity
@Table(name="actividad_investigacion"
    ,catalog="naval"
)
public class ActividadInvestigacion  implements java.io.Serializable {


     private Integer idactividadInvestigacion;
     private Profesor profesor;
     private String codigo;
     private String idProyecto;
     private String responsabilidad;
     private String horasSemanales;
     private Integer anio;
     private Integer periodo;

    public ActividadInvestigacion() {
    }

	
    public ActividadInvestigacion(Profesor profesor) {
        this.profesor = profesor;
    }
    public ActividadInvestigacion(Profesor profesor, String codigo, String idProyecto, String responsabilidad, String horasSemanales, Integer anio, Integer periodo) {
       this.profesor = profesor;
       this.codigo = codigo;
       this.idProyecto = idProyecto;
       this.responsabilidad = responsabilidad;
       this.horasSemanales = horasSemanales;
       this.anio = anio;
       this.periodo = periodo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idactividad_investigacion", unique=true, nullable=false)
    public Integer getIdactividadInvestigacion() {
        return this.idactividadInvestigacion;
    }
    
    public void setIdactividadInvestigacion(Integer idactividadInvestigacion) {
        this.idactividadInvestigacion = idactividadInvestigacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="profesor_idprofesor", nullable=false)
    public Profesor getProfesor() {
        return this.profesor;
    }
    
    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }

    
    @Column(name="codigo", length=45)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="id_proyecto")
    public String getIdProyecto() {
        return this.idProyecto;
    }
    
    public void setIdProyecto(String idProyecto) {
        this.idProyecto = idProyecto;
    }

    
    @Column(name="responsabilidad", length=2000)
    public String getResponsabilidad() {
        return this.responsabilidad;
    }
    
    public void setResponsabilidad(String responsabilidad) {
        this.responsabilidad = responsabilidad;
    }

    
    @Column(name="horas_semanales", length=45)
    public String getHorasSemanales() {
        return this.horasSemanales;
    }
    
    public void setHorasSemanales(String horasSemanales) {
        this.horasSemanales = horasSemanales;
    }

    
    @Column(name="anio")
    public Integer getAnio() {
        return this.anio;
    }
    
    public void setAnio(Integer anio) {
        this.anio = anio;
    }

    
    @Column(name="periodo")
    public Integer getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(Integer periodo) {
        this.periodo = periodo;
    }




}


