package naval.dominio;



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ActividadDocencia generated by hbm2java
 */
@Entity
@Table(name="actividad_docencia"
    ,catalog="naval"
)
public class ActividadDocencia  implements java.io.Serializable {


     private Integer idactividadDocencia;
     private Asignatura asignatura;
     private Curso curso;
     private Profesor profesor;
     private String codigo;
     private Integer horasSemanales;
     private Integer anio;
     private Integer periodo;

    public ActividadDocencia() {
    }

	
    public ActividadDocencia(Asignatura asignatura, Curso curso, Profesor profesor) {
        this.asignatura = asignatura;
        this.curso = curso;
        this.profesor = profesor;
    }
    public ActividadDocencia(Asignatura asignatura, Curso curso, Profesor profesor, String codigo, Integer horasSemanales, Integer anio, Integer periodo) {
       this.asignatura = asignatura;
       this.curso = curso;
       this.profesor = profesor;
       this.codigo = codigo;
       this.horasSemanales = horasSemanales;
       this.anio = anio;
       this.periodo = periodo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idactividad_docencia", unique=true, nullable=false)
    public Integer getIdactividadDocencia() {
        return this.idactividadDocencia;
    }
    
    public void setIdactividadDocencia(Integer idactividadDocencia) {
        this.idactividadDocencia = idactividadDocencia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="asignatura_idasignatura", nullable=false)
    public Asignatura getAsignatura() {
        return this.asignatura;
    }
    
    public void setAsignatura(Asignatura asignatura) {
        this.asignatura = asignatura;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="curso_idcurso", nullable=false)
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="profesor_idprofesor", nullable=false)
    public Profesor getProfesor() {
        return this.profesor;
    }
    
    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }

    
    @Column(name="codigo", length=45)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="horas_semanales")
    public Integer getHorasSemanales() {
        return this.horasSemanales;
    }
    
    public void setHorasSemanales(Integer horasSemanales) {
        this.horasSemanales = horasSemanales;
    }

    
    @Column(name="anio")
    public Integer getAnio() {
        return this.anio;
    }
    
    public void setAnio(Integer anio) {
        this.anio = anio;
    }

    
    @Column(name="periodo")
    public Integer getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(Integer periodo) {
        this.periodo = periodo;
    }




}


