package naval.dominio;



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AdministracionAcademica generated by hbm2java
 */
@Entity
@Table(name="administracion_academica"
    ,catalog="naval"
)
public class AdministracionAcademica  implements java.io.Serializable {


     private Integer idadministracionAcademica;
     private Profesor profesor;
     private String cargoAdministrativo;
     private String actividadesAdministrativas;
     private Integer horasSemanales;
     private Integer anio;
     private Integer periodo;

    public AdministracionAcademica() {
    }

	
    public AdministracionAcademica(Profesor profesor) {
        this.profesor = profesor;
    }
    public AdministracionAcademica(Profesor profesor, String cargoAdministrativo, String actividadesAdministrativas, Integer horasSemanales, Integer anio, Integer periodo) {
       this.profesor = profesor;
       this.cargoAdministrativo = cargoAdministrativo;
       this.actividadesAdministrativas = actividadesAdministrativas;
       this.horasSemanales = horasSemanales;
       this.anio = anio;
       this.periodo = periodo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idadministracion_academica", unique=true, nullable=false)
    public Integer getIdadministracionAcademica() {
        return this.idadministracionAcademica;
    }
    
    public void setIdadministracionAcademica(Integer idadministracionAcademica) {
        this.idadministracionAcademica = idadministracionAcademica;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="profesor_idprofesor", nullable=false)
    public Profesor getProfesor() {
        return this.profesor;
    }
    
    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }

    
    @Column(name="cargo_administrativo")
    public String getCargoAdministrativo() {
        return this.cargoAdministrativo;
    }
    
    public void setCargoAdministrativo(String cargoAdministrativo) {
        this.cargoAdministrativo = cargoAdministrativo;
    }

    
    @Column(name="actividades_administrativas", length=2000)
    public String getActividadesAdministrativas() {
        return this.actividadesAdministrativas;
    }
    
    public void setActividadesAdministrativas(String actividadesAdministrativas) {
        this.actividadesAdministrativas = actividadesAdministrativas;
    }

    
    @Column(name="horas_semanales")
    public Integer getHorasSemanales() {
        return this.horasSemanales;
    }
    
    public void setHorasSemanales(Integer horasSemanales) {
        this.horasSemanales = horasSemanales;
    }

    
    @Column(name="anio")
    public Integer getAnio() {
        return this.anio;
    }
    
    public void setAnio(Integer anio) {
        this.anio = anio;
    }

    
    @Column(name="periodo")
    public Integer getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(Integer periodo) {
        this.periodo = periodo;
    }




}


