package naval.dominio;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Aula generated by hbm2java
 */
@Entity
@Table(name = "aula", catalog = "naval"
)
public class Aula implements java.io.Serializable {

    private Integer idaula;
    private Edificio edificio;
    private String nombre;
    private String tipo;
    private Integer capacidad;
    private String estado;
    private Boolean capacidadAudiovisual;
    private Boolean tablero;
    private Boolean videoBeam;
    private Boolean tv;
    private Integer piso;
    private Set<Mantenimiento> mantenimientos = new HashSet<Mantenimiento>(0);
    private Set<ParteDiario> parteDiarios = new HashSet<ParteDiario>(0);
    private Set<Horario> horarios = new HashSet<Horario>(0);
    private Set<Solicitud> solicituds = new HashSet<Solicitud>(0);
    private Set<Curso> cursos = new HashSet<Curso>(0);

    public Aula() {
    }

    public Aula(Edificio edificio) {
        this.edificio = edificio;
    }

    public Aula(Edificio edificio, String nombre, String tipo, Integer capacidad, String estado, Boolean capacidadAudiovisual, Boolean tablero, Boolean videoBeam, Boolean tv, Integer piso, Set<Mantenimiento> mantenimientos, Set<ParteDiario> parteDiarios, Set<Horario> horarios, Set<Solicitud> solicituds, Set<Curso> cursos) {
        this.edificio = edificio;
        this.nombre = nombre;
        this.tipo = tipo;
        this.capacidad = capacidad;
        this.estado = estado;
        this.capacidadAudiovisual = capacidadAudiovisual;
        this.tablero = tablero;
        this.videoBeam = videoBeam;
        this.tv = tv;
        this.piso = piso;
        this.mantenimientos = mantenimientos;
        this.parteDiarios = parteDiarios;
        this.horarios = horarios;
        this.solicituds = solicituds;
        this.cursos = cursos;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idaula", unique = true, nullable = false)
    public Integer getIdaula() {
        return this.idaula;
    }

    public void setIdaula(Integer idaula) {
        this.idaula = idaula;
    }

    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "edificio_idedificio", nullable = false)
    public Edificio getEdificio() {
        return this.edificio;
    }

    public void setEdificio(Edificio edificio) {
        this.edificio = edificio;
    }

    @Column(name = "nombre", length = 500)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "tipo", length = 500)
    public String getTipo() {
        return this.tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    @Column(name = "capacidad")
    public Integer getCapacidad() {
        return this.capacidad;
    }

    public void setCapacidad(Integer capacidad) {
        this.capacidad = capacidad;
    }

    @Column(name = "estado", length = 500)
    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    @Column(name = "capacidad_audiovisual")
    public Boolean getCapacidadAudiovisual() {
        return this.capacidadAudiovisual;
    }

    public void setCapacidadAudiovisual(Boolean capacidadAudiovisual) {
        this.capacidadAudiovisual = capacidadAudiovisual;
    }

    @Column(name = "tablero")
    public Boolean getTablero() {
        return this.tablero;
    }

    public void setTablero(Boolean tablero) {
        this.tablero = tablero;
    }

    @Column(name = "video_beam")
    public Boolean getVideoBeam() {
        return this.videoBeam;
    }

    public void setVideoBeam(Boolean videoBeam) {
        this.videoBeam = videoBeam;
    }

    @Column(name = "tv")
    public Boolean getTv() {
        return this.tv;
    }

    public void setTv(Boolean tv) {
        this.tv = tv;
    }

    @Column(name = "piso")
    public Integer getPiso() {
        return this.piso;
    }

    public void setPiso(Integer piso) {
        this.piso = piso;
    }

    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "aula")
    public Set<Mantenimiento> getMantenimientos() {
        return this.mantenimientos;
    }

    public void setMantenimientos(Set<Mantenimiento> mantenimientos) {
        this.mantenimientos = mantenimientos;
    }

    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "aula")
    public Set<ParteDiario> getParteDiarios() {
        return this.parteDiarios;
    }

    public void setParteDiarios(Set<ParteDiario> parteDiarios) {
        this.parteDiarios = parteDiarios;
    }

    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "aula")
    public Set<Horario> getHorarios() {
        return this.horarios;
    }

    public void setHorarios(Set<Horario> horarios) {
        this.horarios = horarios;
    }

    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "aula")
    public Set<Solicitud> getSolicituds() {
        return this.solicituds;
    }

    public void setSolicituds(Set<Solicitud> solicituds) {
        this.solicituds = solicituds;
    }

    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "aula")
    public Set<Curso> getCursos() {
        return this.cursos;
    }

    public void setCursos(Set<Curso> cursos) {
        this.cursos = cursos;
    }
}
