package naval.dominio;

import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Curso generated by hbm2java
 */
@Entity
@Table(name = "curso", catalog = "naval"
)
public class Curso implements java.io.Serializable {

    private Integer idcurso;
    private String codigo;
    private Integer numeroEstudiantes;
    private Set<ActividadDocencia> actividadDocencias = new HashSet<ActividadDocencia>(0);
    private Set<ParteDiario> parteDiarios = new HashSet<ParteDiario>(0);
    private Set<ResponsableCurso> responsableCursos = new HashSet<ResponsableCurso>(0);
    private Set<Horario> horarios = new HashSet<Horario>(0);

    public Curso() {
    }

    public Curso(String codigo) {
        this.codigo = codigo;
    }

    public Curso(String codigo, Integer numeroEstudiantes, Set<ActividadDocencia> actividadDocencias, Set<ParteDiario> parteDiarios, Set<ResponsableCurso> responsableCursos, Set<Horario> horarios) {
        this.codigo = codigo;
        this.numeroEstudiantes = numeroEstudiantes;
        this.actividadDocencias = actividadDocencias;
        this.parteDiarios = parteDiarios;
        this.responsableCursos = responsableCursos;
        this.horarios = horarios;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idcurso", unique = true, nullable = false)
    public Integer getIdcurso() {
        return this.idcurso;
    }

    public void setIdcurso(Integer idcurso) {
        this.idcurso = idcurso;
    }

    @Column(name = "codigo", nullable = false, length = 45)
    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    @Column(name = "numero_estudiantes")
    public Integer getNumeroEstudiantes() {
        return this.numeroEstudiantes;
    }

    public void setNumeroEstudiantes(Integer numeroEstudiantes) {
        this.numeroEstudiantes = numeroEstudiantes;
    }

    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "curso")
    public Set<ActividadDocencia> getActividadDocencias() {
        return this.actividadDocencias;
    }

    public void setActividadDocencias(Set<ActividadDocencia> actividadDocencias) {
        this.actividadDocencias = actividadDocencias;
    }

    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "curso")
    public Set<ParteDiario> getParteDiarios() {
        return this.parteDiarios;
    }

    public void setParteDiarios(Set<ParteDiario> parteDiarios) {
        this.parteDiarios = parteDiarios;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "curso")
    public Set<ResponsableCurso> getResponsableCursos() {
        return this.responsableCursos;
    }

    public void setResponsableCursos(Set<ResponsableCurso> responsableCursos) {
        this.responsableCursos = responsableCursos;
    }
    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "curso")
    public Set<Horario> getHorarios() {
        return this.horarios;
    }

    public void setHorarios(Set<Horario> horarios) {
        this.horarios = horarios;
    }

}
