package naval.dominio;
// Generated 21/12/2015 11:03:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DetalleParteDiario generated by hbm2java
 */
@Entity
@Table(name="detalle_parte_diario"
    ,catalog="naval"
)
public class DetalleParteDiario  implements java.io.Serializable {


     private Integer iddetalleParteDiario;
     private DinamicasEmpleadas dinamicasEmpleadas;
     private MotivoInasistenciaEstudiante motivoInasistenciaEstudiante;
     private ParteDiario parteDiario;
     private Integer horaClase;
     private String codigoNombreAsignatura;
     private Date horaInicio;
     private Date horaFinal;
     private String estudiantesFaltantes;
     private String tema;

    public DetalleParteDiario() {
    }

	
    public DetalleParteDiario(DinamicasEmpleadas dinamicasEmpleadas, ParteDiario parteDiario) {
        this.dinamicasEmpleadas = dinamicasEmpleadas;
        this.parteDiario = parteDiario;
    }
    public DetalleParteDiario(DinamicasEmpleadas dinamicasEmpleadas, MotivoInasistenciaEstudiante motivoInasistenciaEstudiante, ParteDiario parteDiario, Integer horaClase, String codigoNombreAsignatura, Date horaInicio, Date horaFinal, String estudiantesFaltantes, String tema) {
       this.dinamicasEmpleadas = dinamicasEmpleadas;
       this.motivoInasistenciaEstudiante = motivoInasistenciaEstudiante;
       this.parteDiario = parteDiario;
       this.horaClase = horaClase;
       this.codigoNombreAsignatura = codigoNombreAsignatura;
       this.horaInicio = horaInicio;
       this.horaFinal = horaFinal;
       this.estudiantesFaltantes = estudiantesFaltantes;
       this.tema = tema;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="iddetalle_parte_diario", unique=true, nullable=false)
    public Integer getIddetalleParteDiario() {
        return this.iddetalleParteDiario;
    }
    
    public void setIddetalleParteDiario(Integer iddetalleParteDiario) {
        this.iddetalleParteDiario = iddetalleParteDiario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="dinamicas_empleadas_iddinamicas_empleadas", nullable=false)
    public DinamicasEmpleadas getDinamicasEmpleadas() {
        return this.dinamicasEmpleadas;
    }
    
    public void setDinamicasEmpleadas(DinamicasEmpleadas dinamicasEmpleadas) {
        this.dinamicasEmpleadas = dinamicasEmpleadas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="motivo_inasistencia_estudiante_idmotivo_inasistencia")
    public MotivoInasistenciaEstudiante getMotivoInasistenciaEstudiante() {
        return this.motivoInasistenciaEstudiante;
    }
    
    public void setMotivoInasistenciaEstudiante(MotivoInasistenciaEstudiante motivoInasistenciaEstudiante) {
        this.motivoInasistenciaEstudiante = motivoInasistenciaEstudiante;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="parte_diario_idparte_diario", nullable=false)
    public ParteDiario getParteDiario() {
        return this.parteDiario;
    }
    
    public void setParteDiario(ParteDiario parteDiario) {
        this.parteDiario = parteDiario;
    }

    
    @Column(name="hora_clase")
    public Integer getHoraClase() {
        return this.horaClase;
    }
    
    public void setHoraClase(Integer horaClase) {
        this.horaClase = horaClase;
    }

    
    @Column(name="codigo_nombre_asignatura", length=1000)
    public String getCodigoNombreAsignatura() {
        return this.codigoNombreAsignatura;
    }
    
    public void setCodigoNombreAsignatura(String codigoNombreAsignatura) {
        this.codigoNombreAsignatura = codigoNombreAsignatura;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="hora_inicio", length=10)
    public Date getHoraInicio() {
        return this.horaInicio;
    }
    
    public void setHoraInicio(Date horaInicio) {
        this.horaInicio = horaInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="hora_final", length=10)
    public Date getHoraFinal() {
        return this.horaFinal;
    }
    
    public void setHoraFinal(Date horaFinal) {
        this.horaFinal = horaFinal;
    }

    
    @Column(name="estudiantes_faltantes", length=45)
    public String getEstudiantesFaltantes() {
        return this.estudiantesFaltantes;
    }
    
    public void setEstudiantesFaltantes(String estudiantesFaltantes) {
        this.estudiantesFaltantes = estudiantesFaltantes;
    }

    
    @Column(name="tema", length=2000)
    public String getTema() {
        return this.tema;
    }
    
    public void setTema(String tema) {
        this.tema = tema;
    }




}


