package naval.dominio;
// Generated 21/12/2015 11:03:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DinamicasEmpleadas generated by hbm2java
 */
@Entity
@Table(name="dinamicas_empleadas"
    ,catalog="naval"
)
public class DinamicasEmpleadas  implements java.io.Serializable {


     private Integer iddinamicasEmpleadas;
     private String codigo;
     private String descripcion;
     private Set<DetalleParteDiario> detalleParteDiarios = new HashSet<DetalleParteDiario>(0);

    public DinamicasEmpleadas() {
    }

    public DinamicasEmpleadas(String codigo, String descripcion, Set<DetalleParteDiario> detalleParteDiarios) {
       this.codigo = codigo;
       this.descripcion = descripcion;
       this.detalleParteDiarios = detalleParteDiarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="iddinamicas_empleadas", unique=true, nullable=false)
    public Integer getIddinamicasEmpleadas() {
        return this.iddinamicasEmpleadas;
    }
    
    public void setIddinamicasEmpleadas(Integer iddinamicasEmpleadas) {
        this.iddinamicasEmpleadas = iddinamicasEmpleadas;
    }

    
    @Column(name="codigo", length=45)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="descripcion", length=500)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dinamicasEmpleadas")
    public Set<DetalleParteDiario> getDetalleParteDiarios() {
        return this.detalleParteDiarios;
    }
    
    public void setDetalleParteDiarios(Set<DetalleParteDiario> detalleParteDiarios) {
        this.detalleParteDiarios = detalleParteDiarios;
    }




}


