package naval.dominio;



import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EstudiosRealizadosDocente generated by hbm2java
 */
@Entity
@Table(name="estudios_realizados_docente"
    ,catalog="naval"
)
public class EstudiosRealizadosDocente  implements java.io.Serializable {


     private Integer idestudiosRealizadosDocente;
     private Profesor profesor;
     private String titulo;
     private Date fechaInicio;
     private Date fechaFinal;
     private String institucionOtorga;

    public EstudiosRealizadosDocente() {
    }

	
    public EstudiosRealizadosDocente(Profesor profesor) {
        this.profesor = profesor;
    }
    public EstudiosRealizadosDocente(Profesor profesor, String titulo, Date fechaInicio, Date fechaFinal, String institucionOtorga) {
       this.profesor = profesor;
       this.titulo = titulo;
       this.fechaInicio = fechaInicio;
       this.fechaFinal = fechaFinal;
       this.institucionOtorga = institucionOtorga;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idestudios_realizados_docente", unique=true, nullable=false)
    public Integer getIdestudiosRealizadosDocente() {
        return this.idestudiosRealizadosDocente;
    }
    
    public void setIdestudiosRealizadosDocente(Integer idestudiosRealizadosDocente) {
        this.idestudiosRealizadosDocente = idestudiosRealizadosDocente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="profesor_idprofesor", nullable=false)
    public Profesor getProfesor() {
        return this.profesor;
    }
    
    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }

    
    @Column(name="titulo")
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_inicio", length=10)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_final", length=10)
    public Date getFechaFinal() {
        return this.fechaFinal;
    }
    
    public void setFechaFinal(Date fechaFinal) {
        this.fechaFinal = fechaFinal;
    }

    
    @Column(name="institucion_otorga")
    public String getInstitucionOtorga() {
        return this.institucionOtorga;
    }
    
    public void setInstitucionOtorga(String institucionOtorga) {
        this.institucionOtorga = institucionOtorga;
    }




}


