package naval.dominio;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Facultad generated by hbm2java
 */
@Entity
@Table(name = "facultad", catalog = "naval"
)
public class Facultad implements java.io.Serializable {

    private Integer idfacultad;
    private String facultad;
    private Set<Programa> programas = new HashSet<Programa>(0);
    private Set<Profesor> profesors = new HashSet<Profesor>(0);
    private Set<ProfesorH> profesorHs = new HashSet<ProfesorH>(0);

    public Facultad() {
    }
    
    public Facultad(String facultad) {
        this.facultad = facultad;
    }

    public Facultad(String facultad, Set<Programa> programas, Set<Profesor> profesors, Set<ProfesorH> profesorHs) {
        this.facultad = facultad;
        this.programas = programas;
        this.profesors = profesors;
        this.profesorHs = profesorHs;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idfacultad", unique = true, nullable = false)
    public Integer getIdfacultad() {
        return this.idfacultad;
    }

    public void setIdfacultad(Integer idfacultad) {
        this.idfacultad = idfacultad;
    }

    @Column(name = "facultad", nullable = false)
    public String getFacultad() {
        return this.facultad;
    }

    public void setFacultad(String facultad) {
        this.facultad = facultad;
    }

    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "facultad")
    public Set<Programa> getProgramas() {
        return this.programas;
    }

    public void setProgramas(Set<Programa> programas) {
        this.programas = programas;
    }
    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "facultad")
    public Set<Profesor> getProfesors() {
        return this.profesors;
    }

    public void setProfesors(Set<Profesor> profesors) {
        this.profesors = profesors;
    }
    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "facultad")
    public Set<ProfesorH> getProfesorHs() {
        return this.profesorHs;
    }

    public void setProfesorHs(Set<ProfesorH> profesorHs) {
        this.profesorHs = profesorHs;
    }
}
