package naval.dominio;
// Generated 21/12/2015 11:03:03 PM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Facultad generated by hbm2java
 */
@Entity
@Table(name = "facultad", catalog = "naval"
)
public class Facultad implements java.io.Serializable {

    private Integer idfacultad;
    private String facultad;
    private Set<Profesor> profesors = new HashSet<Profesor>(0);

    public Facultad() {
    }

    public Facultad(String facultad) {
        this.facultad = facultad;
    }

    public Facultad(String facultad, Set<Profesor> profesors) {
        this.facultad = facultad;
        this.profesors = profesors;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idfacultad", unique = true, nullable = false)
    public Integer getIdfacultad() {
        return this.idfacultad;
    }

    public void setIdfacultad(Integer idfacultad) {
        this.idfacultad = idfacultad;
    }

    @Column(name = "facultad", nullable = false)
    public String getFacultad() {
        return this.facultad;
    }

    public void setFacultad(String facultad) {
        this.facultad = facultad;
    }

    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "facultad")
    public Set<Profesor> getProfesors() {
        return this.profesors;
    }

    public void setProfesors(Set<Profesor> profesors) {
        this.profesors = profesors;
    }

}
