package naval.dominio;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Graduado generated by hbm2java
 */
@Entity
@Table(name = "graduado", catalog = "naval"
)
public class Graduado implements java.io.Serializable {

    private int idgraduado;
    private Programa programa;
    private String primerNombre;
    private String segundoNombre;
    private String primerApellido;
    private String segundoApellido;
    private String tipoId;
    private String numeroId;
    private String categoria;
    private String estado;
    private Date fechaGrado;
    private String correoElectronico;
    private String celular;
    private String direccion;
    private String empresaDondeLabora;
    private String cargo;

    public Graduado() {
    }

    public Graduado(int idgraduado, Programa programa) {
        this.idgraduado = idgraduado;
        this.programa = programa;
    }

    public Graduado(int idgraduado, Programa programa, String primerNombre, String segundoNombre, String primerApellido, String segundoApellido, String tipoId, String numeroId, String categoria, String estado, Date fechaGrado, String correoElectronico, String celular, String direccion, String empresaDondeLabora, String cargo) {
        this.idgraduado = idgraduado;
        this.programa = programa;
        this.primerNombre = primerNombre;
        this.segundoNombre = segundoNombre;
        this.primerApellido = primerApellido;
        this.segundoApellido = segundoApellido;
        this.tipoId = tipoId;
        this.numeroId = numeroId;
        this.categoria = categoria;
        this.estado = estado;
        this.fechaGrado = fechaGrado;
        this.correoElectronico = correoElectronico;
        this.celular = celular;
        this.direccion = direccion;
        this.empresaDondeLabora = empresaDondeLabora;
        this.cargo = cargo;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idgraduado", unique = true, nullable = false)
    public int getIdgraduado() {
        return this.idgraduado;
    }

    public void setIdgraduado(int idgraduado) {
        this.idgraduado = idgraduado;
    }

    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "programa_idprograma", nullable = false)
    public Programa getPrograma() {
        return this.programa;
    }

    public void setPrograma(Programa programa) {
        this.programa = programa;
    }

    @Column(name = "primer_nombre", length = 45)
    public String getPrimerNombre() {
        return this.primerNombre;
    }

    public void setPrimerNombre(String primerNombre) {
        this.primerNombre = primerNombre;
    }

    @Column(name = "segundo_nombre", length = 45)
    public String getSegundoNombre() {
        return this.segundoNombre;
    }

    public void setSegundoNombre(String segundoNombre) {
        this.segundoNombre = segundoNombre;
    }

    @Column(name = "primer_apellido", length = 45)
    public String getPrimerApellido() {
        return this.primerApellido;
    }

    public void setPrimerApellido(String primerApellido) {
        this.primerApellido = primerApellido;
    }

    @Column(name = "segundo_apellido", length = 45)
    public String getSegundoApellido() {
        return this.segundoApellido;
    }

    public void setSegundoApellido(String segundoApellido) {
        this.segundoApellido = segundoApellido;
    }

    @Column(name = "tipo_id", length = 45)
    public String getTipoId() {
        return this.tipoId;
    }

    public void setTipoId(String tipoId) {
        this.tipoId = tipoId;
    }

    @Column(name = "numero_id", length = 45)
    public String getNumeroId() {
        return this.numeroId;
    }

    public void setNumeroId(String numeroId) {
        this.numeroId = numeroId;
    }

    @Column(name = "categoria", length = 45)
    public String getCategoria() {
        return this.categoria;
    }

    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }

    @Column(name = "estado", length = 45)
    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_grado", length = 10)
    public Date getFechaGrado() {
        return this.fechaGrado;
    }

    public void setFechaGrado(Date fechaGrado) {
        this.fechaGrado = fechaGrado;
    }

    @Column(name = "correo_electronico", length = 45)
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }

    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }

    @Column(name = "celular", length = 45)
    public String getCelular() {
        return this.celular;
    }

    public void setCelular(String celular) {
        this.celular = celular;
    }

    @Column(name = "direccion", length = 45)
    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    @Column(name = "empresa_donde_labora", length = 45)
    public String getEmpresaDondeLabora() {
        return this.empresaDondeLabora;
    }

    public void setEmpresaDondeLabora(String empresaDondeLabora) {
        this.empresaDondeLabora = empresaDondeLabora;
    }

    @Column(name = "cargo", length = 45)
    public String getCargo() {
        return this.cargo;
    }

    public void setCargo(String cargo) {
        this.cargo = cargo;
    }

}
