package naval.dominio;
// Generated 21/12/2015 11:03:03 PM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Hora generated by hbm2java
 */
@Entity
@Table(name = "hora", catalog = "naval")
public class Hora implements java.io.Serializable {

    private Integer idhorario;
    private String numero;
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "HH:mm", timezone = "America/Bogota")
    private Date horainicio;
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "HH:mm", timezone = "America/Bogota")
    private Date horafinal;
    private Set<Horario> horarios = new HashSet<Horario>(0);

    public Hora() {
    }

    public Hora(String numero, Date horainicio, Date horafinal, Set<Horario> horarios) {
        this.numero = numero;
        this.horainicio = horainicio;
        this.horafinal = horafinal;
        this.horarios = horarios;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "idhorario", unique = true, nullable = false)
    public Integer getIdhorario() {
        return this.idhorario;
    }

    public void setIdhorario(Integer idhorario) {
        this.idhorario = idhorario;
    }

    @Column(name = "numero")
    public String getNumero() {
        return this.numero;
    }

    public void setNumero(String numero) {
        this.numero = numero;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "horainicio", length = 10)
    public Date getHorainicio() {
        return this.horainicio;
    }

    public void setHorainicio(Date horainicio) {
        this.horainicio = horainicio;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "horafinal", length = 10)
    public Date getHorafinal() {
        return this.horafinal;
    }

    public void setHorafinal(Date horafinal) {
        this.horafinal = horafinal;
    }

    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "hora")
    public Set<Horario> getHorarios() {
        return this.horarios;
    }

    public void setHorarios(Set<Horario> horarios) {
        this.horarios = horarios;
    }
}
