package naval.dominio;
// Generated 4/01/2016 02:32:26 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mantenimiento generated by hbm2java
 */
@Entity
@Table(name="mantenimiento"
    ,catalog="naval"
)
public class Mantenimiento  implements java.io.Serializable {


     private Integer idmantenimiento;
     private Aula aula;
     private Usuario usuarioByTrabajador;
     private Usuario usuarioBySolicitante;
     private Usuario usuarioByAprobadoPor;
     private Date fechaInicio;
     private Date fechaFinal;
     private String descripcion;
     private String prioridad;
     private String tipo;
     private Boolean aprobado;
     private Boolean fueraServicio;
     private Boolean leido;

    public Mantenimiento() {
    }

	
    public Mantenimiento(Aula aula, Usuario usuarioByTrabajador, Usuario usuarioByAprobadoPor, String descripcion) {
        this.aula = aula;
        this.usuarioByTrabajador = usuarioByTrabajador;
        this.usuarioByAprobadoPor = usuarioByAprobadoPor;
        this.descripcion = descripcion;
    }
    public Mantenimiento(Aula aula, Usuario usuarioByTrabajador, Usuario usuarioBySolicitante, Usuario usuarioByAprobadoPor, Date fechaInicio, Date fechaFinal, String descripcion, String prioridad, String tipo, Boolean aprobado, Boolean fueraServicio, Boolean leido) {
       this.aula = aula;
       this.usuarioByTrabajador = usuarioByTrabajador;
       this.usuarioBySolicitante = usuarioBySolicitante;
       this.usuarioByAprobadoPor = usuarioByAprobadoPor;
       this.fechaInicio = fechaInicio;
       this.fechaFinal = fechaFinal;
       this.descripcion = descripcion;
       this.prioridad = prioridad;
       this.tipo = tipo;
       this.aprobado = aprobado;
       this.fueraServicio = fueraServicio;
       this.leido = leido;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idmantenimiento", unique=true, nullable=false)
    public Integer getIdmantenimiento() {
        return this.idmantenimiento;
    }
    
    public void setIdmantenimiento(Integer idmantenimiento) {
        this.idmantenimiento = idmantenimiento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="aula_idaula", nullable=false)
    public Aula getAula() {
        return this.aula;
    }
    
    public void setAula(Aula aula) {
        this.aula = aula;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="trabajador", nullable=false)
    public Usuario getUsuarioByTrabajador() {
        return this.usuarioByTrabajador;
    }
    
    public void setUsuarioByTrabajador(Usuario usuarioByTrabajador) {
        this.usuarioByTrabajador = usuarioByTrabajador;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="solicitante")
    public Usuario getUsuarioBySolicitante() {
        return this.usuarioBySolicitante;
    }
    
    public void setUsuarioBySolicitante(Usuario usuarioBySolicitante) {
        this.usuarioBySolicitante = usuarioBySolicitante;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="aprobado_por", nullable=false)
    public Usuario getUsuarioByAprobadoPor() {
        return this.usuarioByAprobadoPor;
    }
    
    public void setUsuarioByAprobadoPor(Usuario usuarioByAprobadoPor) {
        this.usuarioByAprobadoPor = usuarioByAprobadoPor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_inicio", length=10)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_final", length=10)
    public Date getFechaFinal() {
        return this.fechaFinal;
    }
    
    public void setFechaFinal(Date fechaFinal) {
        this.fechaFinal = fechaFinal;
    }

    
    @Column(name="descripcion", nullable=false, length=2000)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="prioridad", length=45)
    public String getPrioridad() {
        return this.prioridad;
    }
    
    public void setPrioridad(String prioridad) {
        this.prioridad = prioridad;
    }

    
    @Column(name="tipo")
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="aprobado")
    public Boolean getAprobado() {
        return this.aprobado;
    }
    
    public void setAprobado(Boolean aprobado) {
        this.aprobado = aprobado;
    }

    
    @Column(name="fuera_servicio")
    public Boolean getFueraServicio() {
        return this.fueraServicio;
    }
    
    public void setFueraServicio(Boolean fueraServicio) {
        this.fueraServicio = fueraServicio;
    }

    
    @Column(name="leido")
    public Boolean getLeido() {
        return this.leido;
    }
    
    public void setLeido(Boolean leido) {
        this.leido = leido;
    }




}


