package naval.dominio;


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MotivoInasistenciaEstudiante generated by hbm2java
 */
@Entity
@Table(name="motivo_inasistencia_estudiante"
    ,catalog="naval"
)
public class MotivoInasistenciaEstudiante  implements java.io.Serializable {


     private Integer idmotivoInasistencia;
     private String codigo;
     private String descripcion;
     private Set<DetalleParteDiario> detalleParteDiarios = new HashSet<DetalleParteDiario>(0);

    public MotivoInasistenciaEstudiante() {
    }

    public MotivoInasistenciaEstudiante(String codigo, String descripcion, Set<DetalleParteDiario> detalleParteDiarios) {
       this.codigo = codigo;
       this.descripcion = descripcion;
       this.detalleParteDiarios = detalleParteDiarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idmotivo_inasistencia", unique=true, nullable=false)
    public Integer getIdmotivoInasistencia() {
        return this.idmotivoInasistencia;
    }
    
    public void setIdmotivoInasistencia(Integer idmotivoInasistencia) {
        this.idmotivoInasistencia = idmotivoInasistencia;
    }

    
    @Column(name="codigo", length=45)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="descripcion", length=500)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="motivoInasistenciaEstudiante")
    public Set<DetalleParteDiario> getDetalleParteDiarios() {
        return this.detalleParteDiarios;
    }
    
    public void setDetalleParteDiarios(Set<DetalleParteDiario> detalleParteDiarios) {
        this.detalleParteDiarios = detalleParteDiarios;
    }




}


