package naval.dominio;



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ObservacionesGenerales generated by hbm2java
 */
@Entity
@Table(name="observaciones_generales"
    ,catalog="naval"
)
public class ObservacionesGenerales  implements java.io.Serializable {


     private Integer idobservacionesGenerales;
     private Profesor profesor;
     private Integer anio;
     private Integer periodo;
     private String observaciones;

    public ObservacionesGenerales() {
    }

	
    public ObservacionesGenerales(Profesor profesor) {
        this.profesor = profesor;
    }
    public ObservacionesGenerales(Profesor profesor, Integer anio, Integer periodo, String observaciones) {
       this.profesor = profesor;
       this.anio = anio;
       this.periodo = periodo;
       this.observaciones = observaciones;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idobservaciones_generales", unique=true, nullable=false)
    public Integer getIdobservacionesGenerales() {
        return this.idobservacionesGenerales;
    }
    
    public void setIdobservacionesGenerales(Integer idobservacionesGenerales) {
        this.idobservacionesGenerales = idobservacionesGenerales;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="profesor_idprofesor", nullable=false)
    public Profesor getProfesor() {
        return this.profesor;
    }
    
    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }

    
    @Column(name="anio")
    public Integer getAnio() {
        return this.anio;
    }
    
    public void setAnio(Integer anio) {
        this.anio = anio;
    }

    
    @Column(name="periodo")
    public Integer getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(Integer periodo) {
        this.periodo = periodo;
    }

    
    @Column(name="observaciones", length=2500)
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }




}


