package naval.dominio;



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OtrasActividades generated by hbm2java
 */
@Entity
@Table(name="otras_actividades"
    ,catalog="naval"
)
public class OtrasActividades  implements java.io.Serializable {


     private Integer idotrasActividades;
     private Profesor profesor;
     private Integer anio;
     private Integer periodo;
     private String codigo;
     private String idActividad;
     private Integer horasSemanales;

    public OtrasActividades() {
    }

	
    public OtrasActividades(Profesor profesor) {
        this.profesor = profesor;
    }
    public OtrasActividades(Profesor profesor, Integer anio, Integer periodo, String codigo, String idActividad, Integer horasSemanales) {
       this.profesor = profesor;
       this.anio = anio;
       this.periodo = periodo;
       this.codigo = codigo;
       this.idActividad = idActividad;
       this.horasSemanales = horasSemanales;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idotras_actividades", unique=true, nullable=false)
    public Integer getIdotrasActividades() {
        return this.idotrasActividades;
    }
    
    public void setIdotrasActividades(Integer idotrasActividades) {
        this.idotrasActividades = idotrasActividades;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="profesor_idprofesor", nullable=false)
    public Profesor getProfesor() {
        return this.profesor;
    }
    
    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }

    
    @Column(name="anio")
    public Integer getAnio() {
        return this.anio;
    }
    
    public void setAnio(Integer anio) {
        this.anio = anio;
    }

    
    @Column(name="periodo")
    public Integer getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(Integer periodo) {
        this.periodo = periodo;
    }

    
    @Column(name="codigo", length=45)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="id_actividad")
    public String getIdActividad() {
        return this.idActividad;
    }
    
    public void setIdActividad(String idActividad) {
        this.idActividad = idActividad;
    }

    
    @Column(name="horas_semanales")
    public Integer getHorasSemanales() {
        return this.horasSemanales;
    }
    
    public void setHorasSemanales(Integer horasSemanales) {
        this.horasSemanales = horasSemanales;
    }




}


