package naval.dominio;



import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ParteDiario generated by hbm2java
 */
@Entity
@Table(name="parte_diario"
    ,catalog="naval"
)
public class ParteDiario  implements java.io.Serializable {


     private Integer idparteDiario;
     private Aula aula;
     private Curso curso;
     private Dias dias;
     private Date fecha;
     private Set<DetalleParteDiario> detalleParteDiarios = new HashSet<DetalleParteDiario>(0);

    public ParteDiario() {
    }

	
    public ParteDiario(Aula aula, Curso curso, Dias dias) {
        this.aula = aula;
        this.curso = curso;
        this.dias = dias;
    }
    public ParteDiario(Aula aula, Curso curso, Dias dias, Date fecha, Set<DetalleParteDiario> detalleParteDiarios) {
       this.aula = aula;
       this.curso = curso;
       this.dias = dias;
       this.fecha = fecha;
       this.detalleParteDiarios = detalleParteDiarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idparte_diario", unique=true, nullable=false)
    public Integer getIdparteDiario() {
        return this.idparteDiario;
    }
    
    public void setIdparteDiario(Integer idparteDiario) {
        this.idparteDiario = idparteDiario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="aula_idaula", nullable=false)
    public Aula getAula() {
        return this.aula;
    }
    
    public void setAula(Aula aula) {
        this.aula = aula;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="curso_idcurso", nullable=false)
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="dias_iddias", nullable=false)
    public Dias getDias() {
        return this.dias;
    }
    
    public void setDias(Dias dias) {
        this.dias = dias;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="parteDiario")
    public Set<DetalleParteDiario> getDetalleParteDiarios() {
        return this.detalleParteDiarios;
    }
    
    public void setDetalleParteDiarios(Set<DetalleParteDiario> detalleParteDiarios) {
        this.detalleParteDiarios = detalleParteDiarios;
    }




}


