package naval.dominio;



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProfesorH generated by hbm2java
 */
@Entity
@Table(name="profesor_h"
    ,catalog="naval"
)
public class ProfesorH  implements java.io.Serializable {


     private int idprofesorH;
     private Facultad facultad;
     private Integer anio;
     private Integer periodo;
     private String grado;
     private String dedicacionDocente;
     private String tipoContrato;
     private String duracionHoras;
     private String nivelMaxFormacion;
     private Integer porcentajeDocencia;
     private Integer porcentajeInvestigacion;
     private Integer porcentajeAdministrativo;
     private Integer porcentajeBienestarEstudiantil;
     private Integer porcentajeEduNoFormalContinua;
     private Integer porcentajePpextensionNorem;
     private Integer porcentajePpextensionRemu;
     private Integer porcentajeOtrasActividades;
     private Integer numLibrosPublicados;
     private Integer numTextosPublicados;
     private Integer numTextosCalifColciencias;
     private Integer numReportesInvestigacion;
     private Integer numPatentes;
     private Integer premiosNivelNacional;
     private Integer premiosNivelInternacional;

    public ProfesorH() {
    }

	
    public ProfesorH(int idprofesorH, Facultad facultad) {
        this.idprofesorH = idprofesorH;
        this.facultad = facultad;
    }
    public ProfesorH(int idprofesorH, Facultad facultad, Integer anio, Integer periodo, String grado, String dedicacionDocente, String tipoContrato, String duracionHoras, String nivelMaxFormacion, Integer porcentajeDocencia, Integer porcentajeInvestigacion, Integer porcentajeAdministrativo, Integer porcentajeBienestarEstudiantil, Integer porcentajeEduNoFormalContinua, Integer porcentajePpextensionNorem, Integer porcentajePpextensionRemu, Integer porcentajeOtrasActividades, Integer numLibrosPublicados, Integer numTextosPublicados, Integer numTextosCalifColciencias, Integer numReportesInvestigacion, Integer numPatentes, Integer premiosNivelNacional, Integer premiosNivelInternacional) {
       this.idprofesorH = idprofesorH;
       this.facultad = facultad;
       this.anio = anio;
       this.periodo = periodo;
       this.grado = grado;
       this.dedicacionDocente = dedicacionDocente;
       this.tipoContrato = tipoContrato;
       this.duracionHoras = duracionHoras;
       this.nivelMaxFormacion = nivelMaxFormacion;
       this.porcentajeDocencia = porcentajeDocencia;
       this.porcentajeInvestigacion = porcentajeInvestigacion;
       this.porcentajeAdministrativo = porcentajeAdministrativo;
       this.porcentajeBienestarEstudiantil = porcentajeBienestarEstudiantil;
       this.porcentajeEduNoFormalContinua = porcentajeEduNoFormalContinua;
       this.porcentajePpextensionNorem = porcentajePpextensionNorem;
       this.porcentajePpextensionRemu = porcentajePpextensionRemu;
       this.porcentajeOtrasActividades = porcentajeOtrasActividades;
       this.numLibrosPublicados = numLibrosPublicados;
       this.numTextosPublicados = numTextosPublicados;
       this.numTextosCalifColciencias = numTextosCalifColciencias;
       this.numReportesInvestigacion = numReportesInvestigacion;
       this.numPatentes = numPatentes;
       this.premiosNivelNacional = premiosNivelNacional;
       this.premiosNivelInternacional = premiosNivelInternacional;
    }
   
     @Id 

    
    @Column(name="idprofesor_h", unique=true, nullable=false)
    public int getIdprofesorH() {
        return this.idprofesorH;
    }
    
    public void setIdprofesorH(int idprofesorH) {
        this.idprofesorH = idprofesorH;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="facultad_idfacultad", nullable=false)
    public Facultad getFacultad() {
        return this.facultad;
    }
    
    public void setFacultad(Facultad facultad) {
        this.facultad = facultad;
    }

    
    @Column(name="anio")
    public Integer getAnio() {
        return this.anio;
    }
    
    public void setAnio(Integer anio) {
        this.anio = anio;
    }

    
    @Column(name="periodo")
    public Integer getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(Integer periodo) {
        this.periodo = periodo;
    }

    
    @Column(name="grado", length=45)
    public String getGrado() {
        return this.grado;
    }
    
    public void setGrado(String grado) {
        this.grado = grado;
    }

    
    @Column(name="dedicacion_docente", length=45)
    public String getDedicacionDocente() {
        return this.dedicacionDocente;
    }
    
    public void setDedicacionDocente(String dedicacionDocente) {
        this.dedicacionDocente = dedicacionDocente;
    }

    
    @Column(name="tipo_contrato", length=45)
    public String getTipoContrato() {
        return this.tipoContrato;
    }
    
    public void setTipoContrato(String tipoContrato) {
        this.tipoContrato = tipoContrato;
    }

    
    @Column(name="duracion_horas", length=45)
    public String getDuracionHoras() {
        return this.duracionHoras;
    }
    
    public void setDuracionHoras(String duracionHoras) {
        this.duracionHoras = duracionHoras;
    }

    
    @Column(name="nivel_max_formacion", length=45)
    public String getNivelMaxFormacion() {
        return this.nivelMaxFormacion;
    }
    
    public void setNivelMaxFormacion(String nivelMaxFormacion) {
        this.nivelMaxFormacion = nivelMaxFormacion;
    }

    
    @Column(name="porcentaje_docencia")
    public Integer getPorcentajeDocencia() {
        return this.porcentajeDocencia;
    }
    
    public void setPorcentajeDocencia(Integer porcentajeDocencia) {
        this.porcentajeDocencia = porcentajeDocencia;
    }

    
    @Column(name="porcentaje_investigacion")
    public Integer getPorcentajeInvestigacion() {
        return this.porcentajeInvestigacion;
    }
    
    public void setPorcentajeInvestigacion(Integer porcentajeInvestigacion) {
        this.porcentajeInvestigacion = porcentajeInvestigacion;
    }

    
    @Column(name="porcentaje_administrativo")
    public Integer getPorcentajeAdministrativo() {
        return this.porcentajeAdministrativo;
    }
    
    public void setPorcentajeAdministrativo(Integer porcentajeAdministrativo) {
        this.porcentajeAdministrativo = porcentajeAdministrativo;
    }

    
    @Column(name="porcentaje_bienestar_estudiantil")
    public Integer getPorcentajeBienestarEstudiantil() {
        return this.porcentajeBienestarEstudiantil;
    }
    
    public void setPorcentajeBienestarEstudiantil(Integer porcentajeBienestarEstudiantil) {
        this.porcentajeBienestarEstudiantil = porcentajeBienestarEstudiantil;
    }

    
    @Column(name="porcentaje_edu_no_formal_continua")
    public Integer getPorcentajeEduNoFormalContinua() {
        return this.porcentajeEduNoFormalContinua;
    }
    
    public void setPorcentajeEduNoFormalContinua(Integer porcentajeEduNoFormalContinua) {
        this.porcentajeEduNoFormalContinua = porcentajeEduNoFormalContinua;
    }

    
    @Column(name="porcentaje_ppextension_norem")
    public Integer getPorcentajePpextensionNorem() {
        return this.porcentajePpextensionNorem;
    }
    
    public void setPorcentajePpextensionNorem(Integer porcentajePpextensionNorem) {
        this.porcentajePpextensionNorem = porcentajePpextensionNorem;
    }

    
    @Column(name="porcentaje_ppextension_remu")
    public Integer getPorcentajePpextensionRemu() {
        return this.porcentajePpextensionRemu;
    }
    
    public void setPorcentajePpextensionRemu(Integer porcentajePpextensionRemu) {
        this.porcentajePpextensionRemu = porcentajePpextensionRemu;
    }

    
    @Column(name="porcentaje_otras_actividades")
    public Integer getPorcentajeOtrasActividades() {
        return this.porcentajeOtrasActividades;
    }
    
    public void setPorcentajeOtrasActividades(Integer porcentajeOtrasActividades) {
        this.porcentajeOtrasActividades = porcentajeOtrasActividades;
    }

    
    @Column(name="num_libros_publicados")
    public Integer getNumLibrosPublicados() {
        return this.numLibrosPublicados;
    }
    
    public void setNumLibrosPublicados(Integer numLibrosPublicados) {
        this.numLibrosPublicados = numLibrosPublicados;
    }

    
    @Column(name="num_textos_publicados")
    public Integer getNumTextosPublicados() {
        return this.numTextosPublicados;
    }
    
    public void setNumTextosPublicados(Integer numTextosPublicados) {
        this.numTextosPublicados = numTextosPublicados;
    }

    
    @Column(name="num_textos_calif_colciencias")
    public Integer getNumTextosCalifColciencias() {
        return this.numTextosCalifColciencias;
    }
    
    public void setNumTextosCalifColciencias(Integer numTextosCalifColciencias) {
        this.numTextosCalifColciencias = numTextosCalifColciencias;
    }

    
    @Column(name="num_reportes_investigacion")
    public Integer getNumReportesInvestigacion() {
        return this.numReportesInvestigacion;
    }
    
    public void setNumReportesInvestigacion(Integer numReportesInvestigacion) {
        this.numReportesInvestigacion = numReportesInvestigacion;
    }

    
    @Column(name="num_patentes")
    public Integer getNumPatentes() {
        return this.numPatentes;
    }
    
    public void setNumPatentes(Integer numPatentes) {
        this.numPatentes = numPatentes;
    }

    
    @Column(name="premios_nivel_nacional")
    public Integer getPremiosNivelNacional() {
        return this.premiosNivelNacional;
    }
    
    public void setPremiosNivelNacional(Integer premiosNivelNacional) {
        this.premiosNivelNacional = premiosNivelNacional;
    }

    
    @Column(name="premios_nivel_internacional")
    public Integer getPremiosNivelInternacional() {
        return this.premiosNivelInternacional;
    }
    
    public void setPremiosNivelInternacional(Integer premiosNivelInternacional) {
        this.premiosNivelInternacional = premiosNivelInternacional;
    }




}


