package naval.dominio;
// Generated 21/12/2015 11:03:03 PM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Profesor generated by hbm2java
 */
@Entity
@Table(name = "profesor", catalog = "naval"
)
public class Profesor implements java.io.Serializable {

    private Integer idprofesor;
    private Facultad facultad;
    private String codigo;
    private String nombre;
    private Set<Horario> horarios = new HashSet<Horario>(0);

    public Profesor() {
    }

    public Profesor(Facultad facultad, String codigo) {
        this.facultad = facultad;
        this.codigo = codigo;
    }

    public Profesor(Facultad facultad, String codigo, String nombre, Set<Horario> horarios) {
        this.facultad = facultad;
        this.codigo = codigo;
        this.nombre = nombre;
        this.horarios = horarios;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idprofesor", unique = true, nullable = false)
    public Integer getIdprofesor() {
        return this.idprofesor;
    }

    public void setIdprofesor(Integer idprofesor) {
        this.idprofesor = idprofesor;
    }

    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "facultad_idfacultad", nullable = false)
    public Facultad getFacultad() {
        return this.facultad;
    }

    public void setFacultad(Facultad facultad) {
        this.facultad = facultad;
    }

    @Column(name = "codigo", nullable = false)
    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    @Column(name = "nombre", length = 45)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "profesor")
    public Set<Horario> getHorarios() {
        return this.horarios;
    }

    public void setHorarios(Set<Horario> horarios) {
        this.horarios = horarios;
    }

}
