package naval.dominio;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Programa generated by hbm2java
 */
@Entity
@Table(name = "programa", catalog = "naval"
)
public class Programa implements java.io.Serializable {

    private Integer idprograma;
    private Facultad facultad;
    private String nombre;
    private String modalidad;
    private String nivelFormacion;
    private Set<Graduado> graduados = new HashSet<Graduado>(0);

    public Programa() {
    }

    public Programa(Facultad facultad, String nombre) {
        this.facultad = facultad;
        this.nombre = nombre;
    }

    public Programa(Facultad facultad, String nombre, String modalidad, String nivelFormacion, Set<Graduado> graduados) {
        this.facultad = facultad;
        this.nombre = nombre;
        this.modalidad = modalidad;
        this.nivelFormacion = nivelFormacion;
        this.graduados = graduados;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idprograma", unique = true, nullable = false)
    public Integer getIdprograma() {
        return this.idprograma;
    }

    public void setIdprograma(Integer idprograma) {
        this.idprograma = idprograma;
    }

    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "facultad_idfacultad", nullable = false)
    public Facultad getFacultad() {
        return this.facultad;
    }

    public void setFacultad(Facultad facultad) {
        this.facultad = facultad;
    }

    @Column(name = "nombre", nullable = false, length = 45)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "modalidad", length = 45)
    public String getModalidad() {
        return this.modalidad;
    }

    public void setModalidad(String modalidad) {
        this.modalidad = modalidad;
    }

    @Column(name = "nivel_formacion", length = 45)
    public String getNivelFormacion() {
        return this.nivelFormacion;
    }

    public void setNivelFormacion(String nivelFormacion) {
        this.nivelFormacion = nivelFormacion;
    }

    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "programa")
    public Set<Graduado> getGraduados() {
        return this.graduados;
    }

    public void setGraduados(Set<Graduado> graduados) {
        this.graduados = graduados;
    }

}
