package naval.dominio;
// Generated 21/12/2015 11:03:03 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ResponsableCurso generated by hbm2java
 */
@Entity
@Table(name="responsable_curso"
    ,catalog="naval"
)
public class ResponsableCurso  implements java.io.Serializable {


     private Integer idresponsableCurso;
     private Curso curso;
     private String usuario;
     private String nombre;
     private String apellido;
     private String estado;

    public ResponsableCurso() {
    }

	
    public ResponsableCurso(Curso curso) {
        this.curso = curso;
    }
    public ResponsableCurso(Curso curso, String usuario, String nombre, String apellido, String estado) {
       this.curso = curso;
       this.usuario = usuario;
       this.nombre = nombre;
       this.apellido = apellido;
       this.estado = estado;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idresponsable_curso", unique=true, nullable=false)
    public Integer getIdresponsableCurso() {
        return this.idresponsableCurso;
    }
    
    public void setIdresponsableCurso(Integer idresponsableCurso) {
        this.idresponsableCurso = idresponsableCurso;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="curso_idcurso", nullable=false)
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }

    
    @Column(name="usuario", length=45)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellido", length=45)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="estado", length=45)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


