package naval.dominio;
// Generated 21/12/2015 11:03:03 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ResponsableCurso generated by hbm2java
 */
@Entity
@Table(name="responsable_curso"
    ,catalog="naval"
)
public class ResponsableCurso  implements java.io.Serializable {


     private Integer idresponsableCurso;
     private Curso curso;
     private Usuario usuario;

    public ResponsableCurso() {
    }

    public ResponsableCurso(Curso curso, Usuario usuario) {
       this.curso = curso;
       this.usuario = usuario;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idresponsable_curso", unique=true, nullable=false)
    public Integer getIdresponsableCurso() {
        return this.idresponsableCurso;
    }
    
    public void setIdresponsableCurso(Integer idresponsableCurso) {
        this.idresponsableCurso = idresponsableCurso;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="curso_idcurso", nullable=false)
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario_usuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


