package naval.dominio;
// Generated 21/12/2015 11:03:03 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="naval"
)
public class Usuario  implements java.io.Serializable {


     private String usuario;
     private Rol rol;
     private String nombre;
     private String apellido;
     private String password;
     private String estado;

    public Usuario() {
    }

	
    public Usuario(String usuario, Rol rol) {
        this.usuario = usuario;
        this.rol = rol;
    }
    public Usuario(String usuario, Rol rol, String nombre, String apellido, String password, String estado) {
       this.usuario = usuario;
       this.rol = rol;
       this.nombre = nombre;
       this.apellido = apellido;
       this.password = password;
       this.estado = estado;
    }
   
     @Id 

    
    @Column(name="usuario", unique=true, nullable=false)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="rol_codigo", nullable=false)
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }

    
    @Column(name="nombre")
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellido")
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="password", length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="estado", length=45)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


